### ISSUE TITLE
Test will always pass if the template YAML file is empty

### ISSUE THREAD

**Issue by ozooxo** [lrills/helm-unittest#107]
# Problem

If template YAML file is empty, test will alway pass.

# How to reproduce

Below passes as expected.

```
# templates/deployment.yaml
apiVersion: batch/v1beta1
kind: Deployment

---
# tests/deployment_test.yaml
suite: test deployment
templates:
  - deployment.yaml
tests:
  - it: should pass
    values:
      - ../values.yaml
    asserts:
      - isKind:
          of: Deployment
```

Below errors out with `- asserts[0] isKind fail ... Expected kind:	Deployment ...Actual:	null`, as expected.

```
# templates/deployment.yaml
apiVersion: batch/v1beta1

---
# tests/deployment_test.yaml
suite: test deployment
templates:
  - deployment.yaml
tests:
  - it: should pass
    values:
      - ../values.yaml
    asserts:
      - isKind:
          of: Deployment
```

Below passes, but should actually fail:

```
# templates/deployment.yaml
##### Empty file #####

---
# tests/deployment_test.yaml
suite: test deployment
templates:
  - deployment.yaml
tests:
  - it: should pass
    values:
      - ../values.yaml
    asserts:
      - isKind:
          of: Deployment
```

# Environment/Version

I am using the https://hub.docker.com/r/aneeshkj/helm-unittest docker image, which [forks you](https://github.com/aneesh-joseph/helm-unittest) from GitHub. 

# Code

[mychart.zip](https://github.com/lrills/helm-unittest/files/5002529/mychart.zip)
