### ISSUE TITLE
Unable to test multiligne string

### ISSUE THREAD

**Issue by mahjoubwissem** [lrills/helm-unittest#111]
Hello,
I cannot test multiligne variable, like this way : 

credential.yaml : 
```
apiVersion: v1
data:
  credentials.json: |
    {{ .Values.cloudsql.service_account }}
kind: Secret
metadata:
  name: {{ include "cloudsql.fullname" . }}
  labels:
    {{- include "cloudsql.labels" . | nindent 4 }}
type: Opaque
```

tests/credentials_test.yaml : 
```
 - it: should have the same Data
    values:
      - "./values/commons.yaml"
    set:
      cloudsql:
        service_account: test
    asserts:
      - equal:
          path: data.credentials\.json
          value: | 
            test
```

I have this Error : 

**FAIL  Credentials configuration        tests/credentials_test.yaml**
```
        - should have the same Data

                - asserts[0] `equal` fail

                        Path:   data.credentials\.json
                        Expected:
                                test
                        Actual:
                                |
                                  test
                        Diff:
                                --- Expected
                                +++ Actual
```

Any suggestions  ? 
Thank you :)
