### ISSUE TITLE
Test helper functions without adding them to a template

### ISSUE THREAD

**Issue by helgi** [lrills/helm-unittest#21]
Would be good being able to test the helper functions individually/isolated from the templates, still using the same kind of input of values and set tho.

**Comment by lrills** [comment]
Sounds great to me! Would a assertion like below help?
```yaml
- templateEqual:
    template: {{ toYaml (dict "a" "b" "c" "d") }}
    result: |
      a: b
      c: d
```
But this might need to have some hack to implement, maybe swap the templates of chart and render it again.
