### ISSUE TITLE
Error rendering nginx-ingress chart

### ISSUE THREAD

**Issue by claudeatsafe** [lrills/helm-unittest#37]
I am fairly new to helm and just discovered the unittest plugin, so sorry in advance if this is a stupid question. 

I am trying to get the first test running but I am running in a render error in the nginx-ingress chart we have as a dependency for our own chart:

```
### Chart [ xxx ] .

 FAIL  engine deployment	tests/engine_test.yaml
	- should render values
		Error: render error in "xxx/charts/nginx-ingress/templates/controller-service.yaml": template: xxx/charts/nginx-ingress/templates/controller-service.yaml:31:49: executing "xxx/charts/nginx-ingress/templates/controller-service.yaml" at <.Capabilities.KubeVe...>: can't evaluate field GitVersion in type *version.Info


Charts:      1 failed, 0 passed, 1 total
Test Suites: 1 failed, 0 passed, 1 total
Tests:       1 failed, 1 errored, 0 passed, 1 total
Snapshot:    0 passed, 0 total
Time:        12.099274ms
```

Any idea how to resolve this?

requirements.yaml:
```
dependencies:
  - name: nginx-ingress
    repository: '@stable'
    version: 0.16.0
```

requirements.lock
```
dependencies:
- name: nginx-ingress
  repository: https://kubernetes-charts.storage.googleapis.com
  version: 0.16.0
digest: sha256:3a0fa8268f63e59f59afa66445521e249d12ae366aadcc89ac9acf066b3baa86
generated: 2018-05-15T14:28:53.336657485-07:00
```
