### ISSUE TITLE
Multiple templates within test suite

### ISSUE THREAD

**Issue by estahn** [lrills/helm-unittest#38]
I struggle to see the point of multiple templates per test suite. I figured I can use this to test commonalities between the resources, e.g. same labels. But that doesn't work as I have to use the `documentIndex`.

```yaml
suite: General Helm Tests
templates:
  - clusterrolebinding.yaml
  - deployment.yaml
tests:
  - it: should have default labels
    asserts:
      - isNotNull:
          path: metadata.labels.app
      - isNotNull:
          path: metadata.labels.chart
      - isNotNull:
          path: metadata.labels.release
      - isNotNull:
          path: metadata.labels.heritage
```

Is there a way to do this without repeating this all over again?

**Comment by estahn** [comment]
I tried `template:` but that doesn't seem to work as expected.

```yaml
suite: Helm Tests
templates:
  - clusterrolebinding.yaml
  - deployment.yaml
tests:
  - it: should have default labels
    template: deployment.yaml
    asserts:
      - isNotNull:
          path: metadata.labels.app
      - isNotNull:
          path: metadata.labels.chart
      - isNotNull:
          path: metadata.labels.release
      - isNotNull:
          path: metadata.labels.heritage
    set:
      rbac.create: true
```

Output:
```
 FAIL  Helm Tests	tests/helm_test.yaml
	- should have default labels

		- asserts[0] `isNotNull` fail

			Path:	metadata.labels.app
			Expected NOT to be null, got:
				null
```

The `clusterrolebinding.yaml` doesn't have an `app` label but the `deployment.yaml` does.

**Comment by lrills** [comment]
Sorry for latency, try specify the `template:` at `asserts:` level. It should work like:
```
suite: Helm Tests
templates:
  - clusterrolebinding.yaml
  - deployment.yaml
tests:
  - it: should have default labels
    asserts:
      - isNotNull:
          template: deployment.yaml
          path: metadata.labels.app
    set:
      rbac.create: true
```

But `template` at test job level seem to be reasonable, maybe I can add it next patch. :)

**Comment by lrills** [comment]
@estahn, sorry for seeing this so late. Try specify the `template:` at `asserts:` level, it should work like:
```
suite: Helm Tests
templates:
  - clusterrolebinding.yaml
  - deployment.yaml
tests:
  - it: should have default labels
    asserts:
      - isNotNull:
          template: deployment.yaml
          path: metadata.labels.app
    set:
      rbac.create: true
```

But `template` at test job level seem to be reasonable, maybe I can add it next patch. :)
