### ISSUE TITLE
Assertion types for flow-control sprig

### ISSUE THREAD

**Issue by bertpersyn** [lrills/helm-unittest#39]
# Description
Make it possible to assert flow-controls (see sprig) 
# Motivation and Context
It's possible to let the template rendering fail if some conditions are not met: [http://masterminds.github.io/sprig/flow_control.html](flow_control): eg:

```{{- fail "something is not ok" }}``` 
# Example
## _ingress.yaml
```
...
spec:
  rules:
{{- if not .Values.ingress.hosts }}
{{- fail "please provide hosts in yaml format" }}
{{- else }}
...
```
## ingress_test.yaml
```
...
  - it: no hosts provided gives error
    values:
      - ./ingress_test_values.yaml
    set:
      ingress:
        hosts: {}
    asserts:
      - fails:
        contains: "please provide hosts in yaml format"
...
```
