### ISSUE TITLE
Abstraction and printing utility for key-value output

### ISSUE THREAD

**Issue by lrills** [lrills/helm-unittest#5]
And all printing stuff should use it instead of building the line by its own to print something like:
```yaml
Error: an error happen

Expected: 1
Actual: 2
```
and multi-line situation

```yaml
Expected:
  a: b
Actual:
  c: d
```
