### ISSUE TITLE
matchSnapshot should allow to test entire file snapshot instead of just the first document

### ISSUE THREAD

**Issue by RaviDasari** [lrills/helm-unittest#54]
In my scenario, I have multiple documents being declared in the same file.

So my file goes...

# my-project.yaml
```yaml
--- deployment
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
...
--- service
apiVersion: v1
kind: Service
metadata:
...
--- configMap
apiVersion: v1
kind: ConfigMap
metadata:
...
```

But when I try to test snapshot of this file with `matchSnapshot`, I always get the `deployment` object but not the `service` and `configMap` objects snapshot. So I can never test snapshots of the service and configMaps. 

I know the best practice and workaround to this is to separate the documents into different files but before I go with that approach, is there any way we can add that feature to this plugin easily? I am new to go and I don't have a faintest idea on how to write a new plugin so when I looked at the code, I couldn't understand.
