### ISSUE TITLE
Reuse Assertions across different tests

### ISSUE THREAD

**Issue by tony-clarke-amdocs** [lrills/helm-unittest#57]
It would be nice if we could re use the same assertions that are common across different test cases (it). Assume there are 10 assertions a1 to a10 for it1. For it2 there is the same assertions a1 to a10 plus a11. Today, we need to repeat a1 to a10 twice.

**Comment by lrills** [comment]
Sounds good if we can have something like
```yaml
assertionTemplate:
  - name: myAsserts
    template: |
      equal:
        path: some.path.{{ .prop }}
        value: {{ .val }}
     ...
```
and use it like
```yaml
...
- assertions:
    withTemplate:
      name: myAsserts
      args:
        prop: ...
        val: ...
```
so the logic can be easily reuse.

**Comment by lrills** [comment]
Oh and you can alway use yaml template within the same file:
```yaml
- it: test1
  asserts: &myAssert
    - ...
- it: test2
  asserts: *myAssert
```
