### ISSUE TITLE
Unable to parse documents with separator in structured annotations

### ISSUE THREAD

**Issue by floretan** [lrills/helm-unittest#59]
I'm trying to write unit tests for some templates which use ambassador, and I'm getting parsing issues (`Error: yaml: line 7: did not find expected <document start>`) with a service definition that looks similar to example from here https://www.getambassador.io/user-guide/getting-started#3-creating-your-first-route:

```
---
apiVersion: v1
kind: Service
metadata:
  name: httpbin
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  httpbin_mapping
      prefix: /httpbin/
      service: httpbin.org:80
      host_rewrite: httpbin.org
spec:
  ports:
  - name: httpbin
    port: 80
```

It seems that it's specifically the separator `---` in the annotation that is causing parsing issues.
