### ISSUE TITLE
More assertion types

### ISSUE THREAD

**Issue by lrills** [lrills/helm-unittest#6]
### isSubset

```yaml 
isSubset:
  path: metadata.label
  subset:
    a: b
```
### isNotSubset
```yaml 
isNotSubset:
  path: metadata.label
  subset:
    a: b
```

### evaluate
```yaml 
evaluate:
  expression: len(get("spec.template.spec.initContainers")) >= 2
```
check https://github.com/Knetic/govaluate for implementation detail
