### ISSUE TITLE
matchRegex when value is generated in go-template

### ISSUE THREAD

**Issue by mmaier2** [lrills/helm-unittest#61]
Hi,
I'm facing sth:
Let's say I've a chart for a secret and somewhere is

```
stringData:
  database-admin-password: {{ randAlphaNum 16 }}
```

Regardless what I put into a matchRegex assertion test, it's always true, e.g.
```
    asserts:
      - matchRegex:
          path: stringData.database-admin-password
          value: ^-blubb$
```
or
```
    asserts:
      - matchRegex:
          path: stringData.database-admin-password
          value: ^[a-zA-Z0-9_]{16}
```
If I e.g. change that to an equal assertion, like 
```
    asserts:
      - equal:
          path: stringData.database-admin-password
          value: blubb
```
I get
```
		- asserts[0] `equal` fail

			Path:	stringData.database-admin-password
			Expected:
				blubb
			Actual:
				2L6FR6fz2V7c5Pvs
			Diff:
				--- Expected
				+++ Actual
				@@ -1,2 +1,2 @@
				-blubb
				+2L6FR6fz2V7c5Pvs
```

Does the matchRegex assertion somehow has a problem with the gotpl randAlphaNum?

Thanks 
Markus
