### ISSUE TITLE
Feature Enhancement: [notC|c]ontainsAny

### ISSUE THREAD

**Issue by dansiviter** [lrills/helm-unittest#74]
Useful for where you need to verify an entry with a particular value does/doesn't exist but not concerned about the other values. E.g.

**Input**
```
...
      env:
        - name: MY_PARAM
          value: foo  # don't care about this value
```

**Test**
```
asserts:
  - containsAny:
        path: spec.template.spec.containers[0].env
        content:
          name: MY_PARAM
```

This is probably more useful for testing the negative when you want to ensure something doesn't exist via `notContainsAny` when switching on a value. The only way at the moment is verifying the whole structure which can get very verbose and cumbersome to maintain to just check something shouldn't exist.
