### ISSUE TITLE
How to test annotations that have "/" in its path?

### ISSUE THREAD

**Issue by gcavalcante8808** [lrills/helm-unittest#95]
Hi Folks,

I'm trying to evaluate the following tests:

```
      - equal:
          path: metadata.annotations.kubernetes.io/ingress.class
          value: merged
      - equal:
          path: metadata.annotations.merged.ingress.kubernetes.io/config
          value: merged-ingress
```
But I'm receiving the following errors:

![image](https://user-images.githubusercontent.com/640897/72439106-09a1d400-3785-11ea-8cb0-33d1cc3ecceb.png)

How can I run these tests?

Thanks in advance.
